### ISSUE TITLE
Can we crop only signature part from Pan card

### ISSUE THREAD

**Issue by shubh12et1062** [dilippuri/PAN-Card-OCR#12]

**Comment by dilippuri** [comment]
yes, of course, we can. For that, we need to identify the region. Generally, what happens the particular signature area is fixed in such typical kind of documents.

**Comment by shubh12et1062** [comment]
what if we need to pass 15 to 20 thousand pan cards and want to dynamically export signatures at once.

**Comment by dilippuri** [comment]
sure, it can be done by batch processing. just we need to ensure how we are processing. it would, even more, better if we can parallelize it.
